# // Create a User
-- INSERT INTO user (`id`,`appId`,`deviceId`, `created`, `updated`) VALUES ( 0, UUID(), '40403F27-C335-4C79-8D16-574BB22A5544', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP );

-- INSERT INTO user (`id`,`appId`,`deviceId`) VALUES ( 0, UUID(), '40403F27-C335-4C79-8D16-574BB22A5544');
-- UPDATE user SET `username` = 'jmade' WHERE `id` = 1 ;

# User
CREATE TABLE user (id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
username VARCHAR(24),
appId VARCHAR(36),
deviceId VARCHAR(36),
createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP);


# Volume
CREATE TABLE volume (id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
value INT,
userId INT,
updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP);

# Light Strip Status
CREATE TABLE lightStatus (id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
active VARCHAR(1),
process VARCHAR(10),
userId INT,
updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP);


# Background Procs
CREATE TABLE background (id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
pid VARCHAR(10),
name VARCHAR(36),
createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,


#Ammendment statement.
ALTER TABLE [TABLE_NAME] ADD COLUMN [COLUMN_NAME] [DATA_TYPE];

#Update to set default values.
UPDATE [TABLE_NAME] SET [COLUMN_NAME] = [DEFAULT_VALUE] WHERE [COLUMN_NAME] IS NULL;
